version: '3.8'

services:
  drawnix:
    image: registry.qwila.xyz/drawnix:0.1
    container_name: drawnix
    restart: always
    networks:
      - app-default
    environment:
      - VITE_WEBDAV_URL=https://file.qwila.xyz/backup/

networks:
  app-default:
    external: true
